### ISSUE TITLE
editable text area visible in saved pdf

### ISSUE THREAD

**Issue by Mrezagolbaba** [konvajs/konva#1021]
I have a problem with saving as a pdf image. when I want to add text to images and saving as Pdf editable text area visible on the saved file like below. how can I remove the editable area for saving mode?
![Screen Shot 2020-11-30 at 4 59 47 PM](https://user-images.githubusercontent.com/9501814/100615908-869e5380-332d-11eb-9926-ed62ef40cf6b.png)

**Comment by lavrton** [comment]
How do you save to pdf?

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by Mrezagolbaba** [comment]
I used this code to save pdf 
``` document.getElementById('save').addEventListener('click', function () {
            var pdf = new jsPDF('l', 'px', [stage.width(), stage.height()]);
            pdf.setTextColor('#000000');
            stage.find('Text').forEach((text) => {
                const size = text.fontSize() / 0.75; // convert pixels to points
                pdf.setFontSize(size);
                pdf.text(text.text(), text.x(), text.y(), {
                    baseline: 'top',
                    angle: -text.getAbsoluteRotation(),
                });
            });
            pdf.addImage(
                stage.toDataURL({ pixelRatio: 2 }),
                0,
                0,
                stage.width(),
                stage.height()
            );
            pdf.save('canvas.pdf');```

**Comment by lavrton** [comment]
Can you make a demo? Probably you can just remove texts from pdf an export stage as image inside pdf.

**Comment by Mrezagolbaba** [comment]
https://codesandbox.io/s/musing-varahamihira-40e8z?file=/index.html

@lavrton its demo of my problem

**Comment by lavrton** [comment]
[canvas.pdf](https://github.com/konvajs/konva/files/5649802/canvas.pdf)


This a pdf I generated from the demo. The PDF file works ok for me in Chrome. So I am not sure what issue you have.

I am going to close the issue because PDF flow is not a `konva` side. Konva library is about drawing on canvas, not about generation PDF files.

**Comment by heaxo** [comment]
@lavrton Hi, I’d like to ask whether Konva has any plans or recommended approach for exporting directly to PDF.

Specifically, I’m wondering if it’s possible for elements like Text, Line, Rect, etc. to be preserved as vector content in the PDF, instead of being rasterized to a canvas first and then embedded as images.

Currently, using toCanvas / toDataURL together with jsPDF requires very high DPI to achieve acceptable quality, which leads to large file sizes and performance issues. I’m curious if there is any official or suggested way to achieve a more vector-based PDF export.

**Comment by heaxo** [comment]
> skia-canvas

Thank you for your reply.
