### ISSUE TITLE
strokeScaleEnabled ignored when calling getClientRect

### ISSUE THREAD

**Issue by glutentag** [konvajs/konva#1033]
Hello.

Like the title says, `strokeScaleEnabled` seems to be ignored when calling `getClientRect`.
Here is a demo: https://jsbin.com/yebucivoyi/edit?js,console,output.
The y of the green Rect is -40, the same as for the blue Rect with `strokeScaleEnabled` set to true, while I would expect -1 since `strokeScaleEnabled` is set to false.
Same for the height, the green Rect has a height of 480 while I was expecting 402.

Note that calling `getClientRect` relative to its parent is not relevant, the same incorrect y is computed when `getClientRect` is called without `relativeTo`.

So far my temporary fix is to call `getClientRect` with `skipStroke` set to true, and to add manually the stroke.

**Comment by lavrton** [comment]
You are right. We have that bug.

But for now, I have no plans to fix it. And I suggest to use the workaround with `skipStroke: true`.
I am not sure how to make a correct calculation in the case of a scaled group with such a shape inside.

**Comment by testerez** [comment]
Could it be a solution to pass the scale down to each `getClientRect` function, so that it's calculated at scale. I understand that the scale of each element depends on both the scale of the parent and the scale of the current element. But I guess one can be multiplied by the other. That way `getClientRect` would have the correct render scale at each node of the tree.

Does that make sense?

**Comment by lavrton** [comment]
It is not that simple.

I have no idea how to calculate that bounding box if:

1. We have a scaled group
2. The group has a shape with `strokeScaleEnabled = false`


As the solution for your example, you can just use `ignoreStroke` on transformer.
