### ISSUE TITLE
[Feature request] Allow post processing operations

### ISSUE THREAD

**Issue by maloguertin** [konvajs/konva#1114]
Filters are nice but it can be a bit tedious to work on the image data directly. 

Let's say I wanted to create a rectangle with a cut out text inside it, I can do it like that:

https://github.com/konvajs/konva/issues/464

or with a filter that would set alpha 0 for each pixels I want cut out.

It would be nice if I could have something like that

```js
Rect.postProcessingFunc(function (ctx) { 
  ctx.globalCompositeOperation = 'destination-out';
  ctx.fillStyle = 'black';
  ctx.font = "70px Georgia";
  ctx.fillText('Hello', 40, 100);
})
```

Another benefit is that this is way faster than working with `getImageData`

**Comment by lavrton** [comment]
I don't think it is simply possible.

For your example above, `globalCompositeOperation` effects the whole canvas. So it may change/remove drawings of previous shapes. It is not simple to "isolate" such operations. In such situations I am using caching (because cache is creating a new canvas in memory) and several shapes with different `globalCompositeOperation`.

If you need full control over context operations, just use a custom shape: https://konvajs.org/docs/shapes/Custom.html and do you post process there.

**Comment by maloguertin** [comment]
alright thanks
