### ISSUE TITLE
lag issue in version 8.0.2 when using Konva.Transformer with draggable

### ISSUE THREAD

**Issue by rizwan-shr528** [konvajs/konva#1122]
var groupTransformer = new Konva.Transformer();

**Comment by lavrton** [comment]
What is the issue? Demo?

**Comment by rizwan-shr528** [comment]
This is the Demo Link.

 https://jsfiddle.net/a6fy1dzq/3/

Work fine in version 5.0.0 but drag and select does not work in 5.0.0. So we have to use version 8.0.2

**Comment by mrnix** [comment]
Use `cache()` for Text and Group objects. Here is a fix https://jsfiddle.net/1Lwqrj0u/

**Comment by lavrton** [comment]
I found the root of the issue.

There were some fixes about rendering behavior in previous versions.
For your shape, Konva is doing buffer rendering (which is very slow).  To cancel it, just set `perfectDrawEnabled: false` for rectangle shape. Buffer rendering it triggered because your shape has all: fill, stroke and shadow.

https://jsfiddle.net/jrL1goe0/
