### ISSUE TITLE
Don't preventDefault of native events if not dragging happening

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#115]

**Comment by lavrton** [comment]
But is some cases we still need prevent default even without dragging.

Idea: `shape.preventDefault(false)` `true` - is default value

**Comment by albertogasparin** [comment]
+1 on this.
I've noticed that because you are preventing all mouse events on the canvas, that also affects other elements with blur events for instance ([see this example](https://jsfiddle.net/62cx507p/)).

Can we remove this code from mouse events:
```js
// always call preventDefault for desktop events because some browsers
// try to drag and drop the canvas element
if (evt.preventDefault) {
  evt.preventDefault();
}
```

And `return false` on `dragstart` to prevent the native behaviour instead?

**Comment by FireMuse** [comment]
+1 on this, too.
My UI has to go through many hoops to make a draggable scrolling canvas that also takes tap events. Given that this hasn't been marked fix, might I assume some easier workaround exists?

**Comment by lavrton** [comment]
Actually the issue is already resolved in last version: http://konvajs.github.io/docs/events/Mobile_Scrolling.html

Try it.
