### ISSUE TITLE
konva8 layer.clear([bounds])  not work

### ISSUE THREAD

**Issue by jerido** [konvajs/konva#1164]
hi ~
https://unpkg.com/konva@8/konva.min.js
layer.clear([bounds])  not work

https://unpkg.com/konva@7.2.5/konva.min.js
it work

https://jsbin.com/nolumoj/4/edit?html,css,js,output

**Comment by lavrton** [comment]
It is because of automatic re-render from `konva@8`. Konva is doing full rendering again on the next frame. So we see just a rectangle again. https://konvajs.org/api/Konva.html#.autoDrawEnabled

I think using `clear` method is anti-pattern for Konva usage. I am going to remove this method from docs and deprecate it.
