### ISSUE TITLE
caching a custom shape

### ISSUE THREAD

**Issue by echo66** [konvajs/konva#118]
Greetings!

I'm trying to use 'triangle.cache()' in the official demo for Custom Shapes. Unfortunately, when I execute 'stage.draw()', the shape disappears. Is custom shape caching supported? If yes, does it work differently?

Thanks in advance

**Comment by lavrton** [comment]
Look at `cache()` documentation. http://konvajs.github.io/api/Konva.Node.html#toc11

It is not possible to detect bounding box for custom shape. So you have to pass bounding box attrs to `cache` function manually.
```javascript
triangle.cache({
  x: 20, y: 50,
  width: 240, height: 120,
  offset: 2  // add some offset for stroke
});
```
http://jsbin.com/matoba/edit?html,js,output

**Comment by echo66** [comment]
thanks for the explanation, @lavrton  :+1:

**Comment by echo66** [comment]
@lavrton , one related question: If I can set a custom shape as draggable and, as such, drag it around, why can't the same hit box be used to cache the shape? Is there a difference?

**Comment by lavrton** [comment]
@echo66 because hit detection works differently, without box calculation.
If you are interested how it works: it draws all shapes into another off-screen canvas with different colors for each shape. Then to detect shape in a position we need to get color of the pixel in canvas, and then find shape with this color.

**Comment by echo66** [comment]
oooh ok ok. Thanks for the intuitive explanation, @lavrton ! :D
