### ISSUE TITLE
Please add skew on transformer with mouse events

### ISSUE THREAD

**Issue by ganeshpatwaypi** [konvajs/konva#1248]
i tried but not as expected i want left top right bottom skew
https://output.jsbin.com/yuhused/

**Comment by ganeshpatwaypi** [comment]
i tried but not as expected i want left top right bottom skew 
https://output.jsbin.com/yuhused/

**Comment by lavrton** [comment]
Sorry, I don't understand what you want. Do you want to change skew from an additional anchor? How do you expect it to work?

**Comment by ganeshpatwaypi** [comment]
@lavrton yes i want with additional anchor to skew the object on mouse events as konva does not have anchors for skew.
I am not able to archive as required result 
problem :  during skew from any side, apposite side should also move to make our shape skewed. But  apposite side does not move during skew. 
and what I expect during  skew  : [](https://drive.google.com/file/d/15un59VNrW56WEozyq-9Upt4YGNY9VTyB/view?usp=sharing)

it  may be some more calculation required

**Comment by ganeshpatwaypi** [comment]
@lavrton any updates on this

**Comment by lavrton** [comment]
You may try to use offset to set the origin of the shape to it center. So changing skew will move apposite side. 
https://jsbin.com/facudowere/1/edit?html,css,js,output

Or you can calculate new {x,y} of the rectangle by yourself. 

I am closing the issue because there is nothing to do from the Konva side. `Konva.Transformer` is not designed to work with skew, as it is demonstrated in the video. If you want to have the same behavior, you should make your own controls/anchors to change skew, position, size.

**Comment by ganeshpatwaypi** [comment]
@lavrton Thanks a lot !!! you are fantastic minded person.

**Comment by ganeshpatwaypi** [comment]
Hi @lavrton  as last discussion i have achieved the expected functionality as per your guidance. now i am facing issue with rotation when i am rotating shape then doing skew it is not working as 0 rotation

https://jsbin.com/rucehil/edit?js,console,output

**Comment by lavrton** [comment]
I don't understand the demo.

**Comment by ganeshpatwaypi** [comment]
check this link rotate and skew.  skew icon will appear on mouse over on the borders
https://jsbin.com/babagef/edit?html,js,output
