### ISSUE TITLE
getAbsoluteTransform doesn't seem to account for stage scale.

### ISSUE THREAD

**Issue by dhalldmg** [konvajs/konva#1256]
It seems that when a Konva Line is transformed there is a problem in the calculations of new points if the stage is scaled.  The result is that the line jumps position after the new points are applied.

To reproduce try transforming the line with and without line "stage.scale({x:0.9,y:0.7})" commented out.
https://jsbin.com/tofogirene/edit?html,js,output

**Comment by lavrton** [comment]
It jumps because `getAbsoluteTransform()` is taking stage scale into account. But updating points based on absolute transformer doesn't make much sense to me. If you want to reset scale, you probably want to use `getTransform()` instead for relative transformation.

**Comment by dhalldmg** [comment]
Thank you for your response, I see that difference now.

**Comment by Ovchinnikov58** [comment]
Hi. If I am trying use getTransform() into child of group, i can not get current points of polygon. What can i use with stage sccale? 

demo: https://codesandbox.io/s/wonderful-tree-49utnt

**Comment by harrisjm3** [comment]
@lavrton In the above example, Notice how rotating the shape messes up the calculations. What is the proper way to account for rotation when rotating a shape and also accounting for that on subsequent drag events?

**Comment by lavrton** [comment]
In that example, stage has different scaleX and scaleY. Because of that, `skewX` and `skewY` attributes are entering into the room of transformations. So that may mess everything. This should work better:

```js

var width = window.innerWidth;
var height = window.innerHeight;

var stage = new Konva.Stage({
  container: 'editor-body',
  width: width,
  height: height,
});
stage.scale({x:1.5,y: 1});

var layer = new Konva.Layer();

var redLine = new Konva.Line({
  points: [50, 50, 150, 50, 150, 150, 50, 400],
  stroke: 'red',
  strokeWidth: 10,
  lineCap: 'round',
  lineJoin: 'round',
  closed:true,
  draggable:true
});

redLine.on('transformend dragend', (e) => {
  const oldPoints = redLine.points();
  const newPoints = [];

  for(var i = 0; i< oldPoints.length / 2; i++) {
    const point = redLine.getAbsoluteTransform(stage).point({
      x: oldPoints[i * 2],
      y: oldPoints[i * 2 + 1]
    });
    newPoints.push(point.x, point.y);
  }
  redLine.points(newPoints);
  redLine.scaleX(1);
  redLine.scaleY(1);
  redLine.skewX(0);
  redLine.skewY(0);
  redLine.rotation(0);
  redLine.x(0);
  redLine.y(0);
});

var tr=new Konva.Transformer({draggable:true,nodes:[redLine], ignoreStroke: true});
layer.add(redLine, tr);
stage.add(layer);
```

https://jsbin.com/hesuqorizi/3/edit?js,output

**Comment by harrisjm3** [comment]
This is great. I think what has thrown me off in react-konva is that you still need to adjust the event.target along with state, otherwise they are out of sync and push and pull a shape away from the expected location. 

Another question, How can I maintain the transformer in it's rotated state vs the transformer reconfiguring to show the container upright? 
![image](https://github.com/user-attachments/assets/c3839d80-27c6-4abc-bea5-255b184ed1e7)
![image](https://github.com/user-attachments/assets/1f944bb3-a226-4d27-a300-b6d726826d05)

I need to show the user the degrees a shape has been rotated and to me it won't look intuitive if the transformer switches from its rotated state to an upright position.
