### ISSUE TITLE
React Konva Image Flickering after change the filter state

### ISSUE THREAD

**Issue by helloindra** [konvajs/konva#1265]
Helo, i am not sure how to fix this.

So i wanted to create color tint effect on an image.

https://user-images.githubusercontent.com/75231253/148492018-cc9279cb-5d68-4f59-919b-eee5584af86b.mp4

But its keep on Flickering like in the video.

Is there any advice ?
<img width="722" alt="image" src="https://user-images.githubusercontent.com/75231253/148493183-36a25c0e-ab56-4f72-b456-600f14e91565.png">

**Comment by lavrton** [comment]
You have flickering because React mount/unmount image on every update. 
You generate new component function `Layer1` inside render of `App`. As it is a new function reference on every update, React thinks it is a new component. So, it has to unmount/mount it.
To solve the issue, just move your Layer1 from App render.

```js
const Layer1 = () => {
  // image component here
}

const App = () => {
  return <Stage><Layer><Layer1/></Layer></Stage>
}
```
