### ISSUE TITLE
Using Stage as relative to getClientRect()

### ISSUE THREAD

**Issue by RageCrezz** [konvajs/konva#1291]
Hey there,

I am currently confronting an issue regarding the `getClientRect()` function.
To fancy my zoom controls, I am trying to get the client rect of the Stage itself, to zoom the Stage to the client rect of all content visible on the Stage.

For now I am defining the line as:
`relativeTo: this.stage as unknown as Container<Node<NodeConfig>>` 

Before that, I've defined it as `any`, which is also not practical in this case.

I'd like to know the correct way of implementing the `relativeTo` for the Stage itself. Thanks in advance!

Best regards.

**Comment by lavrton** [comment]
So, what is your issue/error? Do you have just an error with typescript? What type of `this.stage`? If it is `Konva.Stage` it should work just fine.

**Comment by RageCrezz** [comment]
It's a TypeScript error, yes. `this.stage` is type of `Konva.Stage` so it should work out, although when I set `relativeTo: this.stage`, then I get the error:
`Type 'Stage' is not assignable to type 'Container<Node<NodeConfig>>'.`

**Comment by lavrton** [comment]
I don't know why it doesn't work. Probably you have some very strict TypeScript rules. I suggest to just ignore it. `this.stage as any`.

**Comment by markcnunes** [comment]
I am having the same issue.

Here is the error:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/18724600/187956258-81e9ba4f-ed78-4921-b72a-ff90a91adfd5.png">

Reproducible example:
https://codesandbox.io/s/issue-related-to-getclientrect-relativeto-5ssdgk

This example is using the basic Typescript rules:
```json
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  }
}
```

Perhaps `relateTo` could be more generic because the `Konva.Layer` becomes more than just `Container<Node<ContainerConfig>>` we can confirm that by replacing `Stage extends Container<Layer> {` with `Stage extends Container<Node<ContainerConfig>> {` and that error goes away, I am aware this is not the solution, but just wanted to show an example of how the generic type might be a solution for that issue.

Or if the solution is for us to use `stage as any` then perhaps we could change the type `relativeTo?: Container<Node>;` to `relativeTo?: Container<any>`.
