### ISSUE TITLE
evt.stopImmediatePropagation fails to stop second+ event listener on same object

### ISSUE THREAD

**Issue by VanquishedWombat** [konvajs/konva#1319]
### Note

I am raising this issue to track it somewhere formal as it was mentioned in the Discord today.

### Issue:  evt.stopImmediatePropagation fails to stop second+ event listener on same object

Simple demo - one shape on one layer. Set TWO onclick listeners on the shape. In code for first listener include the line 

`evt.stopImmediatePropagation();`

The SECOND listener will still be firecd, even though evt.stopImmediatePropagation() should stop any further listeners of the same event from beingfired. See [MSDN page here](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation).

It could be that Konva's event setup is not an exact parallel to the generic JS event so it may not be possible to follow the JS function precisely. 

### Workaround

In the Discord, @Anton, the developer stated "I don't have plans to support stopImmediatePropagation inside Konva. Just do one event and do all check inside." 

### Conclusion

@Anton I am not concerned if you want to immediately close this issue. I just wanted to record it so that anyone searching in the future will find it and understand the position.

**Comment by lavrton** [comment]
@VanquishedWombat thanks for creating this note. Here is a quick example code that reproduce the issue.

```js
circle.on('click', function (evt) {
     evt.evt.stopImmediatePropagation()
});
      
circle.on('click', function (evt) {
  alert('Propagation!');
});
```

When you click on the circle, both events will be triggered. 

Konva event system is  syntactic. It tries to follow most common event flows from DOM events such as bubbling, cancelation, etc. But it doesn't work in 100% spec.

`evt` argument passed into event callback is just a simple syntactic event object. This object has reference to real native DOM event `evt.evt`. **Any changes or function calls in native event object do not change flow of Konva event system.** Because DOM events and Konva events are very different worlds.

So calling `evt.evt.stopImmediatePropagation()` does not have any effects and the second event is still triggered.
