### ISSUE TITLE
stage mousemove position occasional error

### ISSUE THREAD

**Issue by Emily-0616** [konvajs/konva#1350]
Why return the coordinates of the upper left corner？

[demo](https://codesandbox.io/s/funny-ganguly-h5usk6?file=/src/index.js)

**Comment by lavrton** [comment]
```js
onMouseMove={({ target }) => {
        const { x, y } = target.getRelativePointerPosition();
        setCurrent({ x, y });
}}
```

When you are on empty white space, it will return the absolute position of the pointer.
It will call setState and move the circle
On the next `mousemove`, `target` will be circle. Because mouse is over it.
So `target.getRelativePointerPosition()` will return position relative to circle. It will be close to its center. So it will be near zero.
That will move circle back to left corner.

You can use `currentTarget.getPointerPosition()` instead.
