### ISSUE TITLE
Linear gradient on polygon not working

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1408]
For some reason Konva is not drawing a linear gradient on a polygon I'm drawing.  I think I have the gradient specification right because the same spec on a rectangle works.  This is the code:

```
// Polygon
layer.add(new Konva.Line({
	"points": [
		250, 150,
		350, 150,
		350, 250,
		250, 250,
	],
	"fillLinearGradientStartPoint": { "x": -1, "y": -5 },
	"fillLinearGradientEndPoint": { "x": 60, "y": 70 },
	"fillLinearGradientColorStops": [0, "red", 1, "yellow"],
	"closed": true,
}));

// Rectangle
layer.add(
	new Konva.Rect({
		x: 250,
		y: 30,
		width: 150,
		height: 100,
		"fillLinearGradientStartPoint": { "x": -1, "y": -5 },
		"fillLinearGradientEndPoint": { "x": 60, "y": 70 },
		"fillLinearGradientColorStops": [0, "red", 1, "yellow"],
	})
);

stage.add(layer);
```

And the result; polygon at the bottom:

![result](https://user-images.githubusercontent.com/793830/191497537-43cce7d5-197a-490a-96c3-d4a8200053e9.png)

Why doesn't the polygon get the linear gradient?  The same seems to apply to radial gradients:

![result2](https://user-images.githubusercontent.com/793830/191498148-2a68db1e-c1b3-440d-a2b9-cb803edfc0b0.png)

Do polygons not support gradients?

**Comment by lavrton** [comment]
It is not related to stage. It is related to origin of the shape (its `x` and `y`). You have large numbers in your `points`, so you don't see gradient. Because `points` are far from origin. If you want to see it, just set points close to the origin. And then move polygon with `x` and `y` if you want to have it on another place. https://jsbin.com/necixejuva/2/edit?html,js,output
