### ISSUE TITLE
Change transformer rotation origin for rectangle

### ISSUE THREAD

**Issue by punowo** [konvajs/konva#1711]
Hello. 
I've noticed that when I add a transformer on a rectangle it rotates the rectangle from the center instead of its top left point. Is there any way I can change this without manually implementing the rotation ?

**Comment by lavrton** [comment]
No, currently `Konva.Transformer` has no API to control that.

**Comment by nighca** [comment]
@lavrton I'd like to refactor the `Transformer` class to allow subclasses to easily modify its rotation and scaling origin. This would involve extracting hook methods, such as `protected getOrigin(): { x: number, y: number }`, while maintaining current behavior of the `Transformer` class. Would a pull request implementing this be acceptable?

**Comment by lavrton** [comment]
@nighca what is the use case?

**Comment by nighca** [comment]
@lavrton We are using Konva.js to develop the "preview stage" for a 2D game editor. Sprites are rendered as Konva nodes on the stage and can be transformed using the Konva Transformer. Since different sprites may have distinct pivots, it would enhance user experience to rotate and scale around the sprite's pivot during transformation.
