### ISSUE TITLE
Set opacity to Layer does not work properly

### ISSUE THREAD

**Issue by boikovdv** [konvajs/konva#234]
Setting opacity to Layer result opacity each shape itself.
But expected result is setting opacity to Layer canvas.
Example: https://jsbin.com/tafubozosa/edit?html,js,output

**Comment by lavrton** [comment]
Yes. That makes sense. But it is hard to solve in a good way.

Setting opacity on just a canvas (by CSS) will take a lot of work because we will need to add special logic for converting a layer to image and to dataURL and probably in many other places.

So from this point, I don't have any plans to fix it.
As workaround, you can cache a layer: https://jsbin.com/bimumugusi/1/edit?html,js,output

**Comment by lavrton** [comment]
Closing the issue for now. I don't think we need such behavior built-in.
