### ISSUE TITLE
large memory useage in safari

### ISSUE THREAD

**Issue by feixinghong** [konvajs/konva#275]
large memory useage in safari ， when  i use konva in safari , lage use of safari. but in chrome it is okay.maybe chrome has a very nice GC

**Comment by lavrton** [comment]
Not sure what can we do here from `konva` side.

Do you have many objects on the canvas?

**Comment by lavrton** [comment]
Also take a look here: https://konvajs.github.io/docs/performance/Avoid_Memory_Leaks.html

Add a comment if you still have issues.

**Comment by ThomasRossi** [comment]
I can confirm the same behaviour, on Chrome and Firefox a simple page works fine (3 groups, each with 10-ish circles inside, on click of a group a Transformer is attached, on click on the main stage, Transformer is destroyed) on Safari it's really slow, although I don't see a big memory consumption. Another interesting thing is that the animations complete beyond their time. Let me know if you need something in particular to debug.

**Comment by lavrton** [comment]
@ThomasRossi do you have a demo?

**Comment by ThomasRossi** [comment]
Yea, http://jsfiddle.net/0va9zrde/ 

just found out it's the opacity, you can try and change the opacity at line 110, put 1 and it works smooth also in Safari. I just created the groups because I thought it has something to do with children inside groups, but nope, you can reproduce it with a couple of objects. I've checked also the timelines of js events and they are the same in Chrome and Safari (that is what made me think the children and groups had nothing to do with it).

**Comment by lavrton** [comment]
This demo is slow because of some extra work required for opacity objects with stroke. You can simply disable that behavior: https://konvajs.github.io/docs/performance/Disable_Perfect_Draw.html
