### ISSUE TITLE
Performance issues with _getIntersection() on FF and IE/Edge

### ISSUE THREAD

**Issue by Y0lk** [konvajs/konva#293]
I have an app that deals with large images that can be scaled, rotated, etc. It runs perfectly in Chrome / Safari but in FF and Edge, when I have big images, the performance suddenly drops and it becomes completely unusable.

I found that the problem was due to **_getIntersection()** which is called on all mouse events, and more specifically, **getImageData()**. From my tests, **getImageData()** becomes very slow in Firefox or Edge when you have big canvases and are using a lot of memory.

By analyzing the code, I found that it never caches the imageData, and I was wondering why. Then, I found the **_getImageData()** method that does exactly that (and  you can get a slight performance increase by caching the result of **getImageData().data** instead of just **getImageData()**). For some reason though, that method is never used. I modified **_getIntersection()** to use **_getImageData()** and it went from unusuable to nearly 60fps.

I found this commit from 2014, "disable layer hit caching" where the change happened: https://github.com/konvajs/konva/commit/9fba09008f202b61c437ebd8a81cbec0b6ed8e30#diff-b97124864856432df2f3ab3a5fa12871

Why is that? Why was it disabled?

**Comment by lavrton** [comment]
> Why is that? Why was it disabled?

With my tests, the code with caching `getImageData()` was slower. `getImageData` of a whole canvas is a slow operation. It should work much faster for 1px area (as it works right now).
Also when using the cache we need to write a lot of code for cache invalidation. I was not sure this is useful because of no performance improvements.

Probably we can enable optional caching, as it may work well in [some] cases.

**Comment by Y0lk** [comment]
I see. It makese sense and I can definitely see that it works well in Chrome / Safari.

However in Firefox at least, it doesn't seem like calling getImageData on a single pixel helps. Caching the data instead makes a big difference, but maybe that's only when you're working with big images (like in my case). Optional caching seems like a good idea.

**Comment by kromit** [comment]
Update: `getImageData()` works somewhat fine in FF now, but chrome (at least on linux) and iOS... Oh boy.  `onmousemove` is extremely choppy and eats up about [80% of CPU](https://i.imgur.com/odTk4hc.png), the memory literally evaporates so the garbage collector runs every 100-300ms. It is not possible to draw free hand because of low the frame rate, and consequentially low event rate, so you cant draw a smooth shape like a free hand circle (line with points).

Can we please disable this? Why is it even needed for mousemove or drag?

**Comment by lavrton** [comment]
This is how a hit detection works in `Konva`.

How many layers do you have? You can disable hit detecting temporary, while drawing the line, with `layer.hitGraphEnabled(false)`. In that case, it will not call `getImageData()`

**Comment by kromit** [comment]
Thank you for quick response. I will try it. I am using only one Layer.

**Comment by lavrton** [comment]
Closing the issue. I am not sure how we can improve the performance here.
