### ISSUE TITLE
Can not clone stage

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#510]
Currently, it is not possible to clone a stage and reuse it. Cloning doesn't handle container change correctly.

```javascript
var cloned_stage = stage.clone();
cloned_stage.setContainer("container2");
cloned_stage.draw();
```

It this code expected result is new canvases in `container2`. But they are not here.

https://jsbin.com/kugabahoko/1/edit?html,js,output

As workaround we can convert stage into JSON and then recreate a stage from JSON.

**Comment by wuhaochen** [comment]
Hi there, I got a similar issue recently when trying to use Vue-Konva to create two stages with the same vue component.

Traceback I got:
```
TypeError: Cannot read property 'removeChild' of null
    at Stage.setContainer (Stage.js?eba4:99)
    at Stage.constructor.<computed> [as container] (Factory.js?f0b4:77)
    at VueComponent.mounted (vue-konva.js?7591:308)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
    at Object.insert (vue.runtime.esm.js?2b0e:3139)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6340)
    at Vue.patch [as __patch__] (vue.runtime.esm.js?2b0e:6559)
    at Vue._update (vue.runtime.esm.js?2b0e:3939)
    at Vue.updateComponent (vue.runtime.esm.js?2b0e:4060)
```

I think the issue is because the `parentElement` for the stage is a const `fakeContainer` and got destroyed at some point and the change here is going to try to call the `removeChild` on a `null` element.

Do you think it is reasonable to change `if (this.content)` to `if (this.content && this.content.parentElement)`?

I can try to create a minimum example if you think that is necessary.
(Basically made a Vue component including a v-stage and used it twice side by side.)

**Comment by lavrton** [comment]
@wuhaochen please create a demo? Why do you need to clone the stage in `vue` app?

**Comment by wuhaochen** [comment]
Hi @lavrton , I'm not able to reproduce the problem with jsfiddle or other service, however the issue shows up almost consistently when I'm trying to use `npm run serve` to test locally. Based on the Traceback, I suspect this is related to how npm update the page when source code changes.

The code I was using is basically https://codesandbox.io/s/vuekonvatemplate-d863r?fontsize=14 .

The current logic seems to be potentially problematic when the stage has no parents, I'm not sure if this is something that we can safely assume. I'd suggest change https://github.com/konvajs/konva/blob/4a398a0aaeec5fb4880ad3d4c6fdce58898bd612/src/Stage.ts#L192-L195 to
```
 if (this.content && this.content.parentElement) { 
   this.content.parentElement.removeChild(this.content); 
 }
 container.appendChild(this.content); 
```

I can send a PR but I'm not sure what is the best way to test the change. Any suggestions? Thanks.

**Comment by lavrton** [comment]
I can't see cases when `this.content.parentElement` is null.

**Comment by wuhaochen** [comment]
This happened to me (See the traceback). It is possible it only happens with edge case like this. (My suspicion is that the fakeContainer used to create the stage got deleted before the new container was set because of it is reused but I'm having a hard time to trace through npm development tools.)

On the other hand I don't see any potential issue with checking `this.content.parentElement` before calling `removeChild` on it. Do you have specific concerns there?

**Comment by lavrton** [comment]
We can add that check. If you want, make a Pull Request.
