### ISSUE TITLE
best practice to define a custom shape?

### ISSUE THREAD

**Issue by zzzgit** [konvajs/konva#539]
Hi guys, which is the best practice to define a custom shape?
1. `new Konva.Shape({})`
2. `class NewShape extends Konva.Shape{}`

I think the second one is better because by that way I can instantiate an instance every time I need it. However, there is no official demo for that.

**Comment by lavrton** [comment]
The second approach is a bit more efficient. But the difference is very small. For most of the apps creating `new Konva.Shape({})` will be enough.

Possibly I will create official demo for the class usage. For now, you can use Konva source in the repo as a demo (see simple shapes such as Circle).

> I can instantiate an instance every time I need it

Right. For the first approach you can just do this:

```javascript
function createShape() {
    return new Konva.Shape({
        // some props here
    });
}

// now every time you need a shape you just do this:
const shape = createShape();
layer.add(shape);
```

**Comment by catanon** [comment]
I'm looking for something different. Instead of creating a new shape, I want to extend old shapes to add more properties and methods. Something like this [JavaFX example](https://stackoverflow.com/a/31571108). Is it a good idea to just add new properties to the objects (e.g. Rect)?

I am especially interested in extending Group, so that when I instantiate this new class, there have already been some children in the Group.

**Comment by lavrton** [comment]
Sure. Just try not to use any private and non-documented properties and methods.

**Comment by catanon** [comment]
Would it interfere with the (de)serialization?

**Comment by lavrton** [comment]
Yes. You just may need to register the shape for correct deserialization. Something like this.

```js
import { _registerNode } from 'konva/lib/Global';
import { Shape, ShapeConfig } from 'konva/Shape';

class MyShape extends Shape {}

MyShape.prototype.className = 'MyShape';
_registerNode(MyShape);
```
