### ISSUE TITLE
.find() by multiple names on same object #enhancement

### ISSUE THREAD

**Issue by dheil** [konvajs/konva#604]
Hi, it would be nice, if one could search for an object that has multiple names specified:

```
Rect1.name = "name1 name2 name3"  
Rect2.name = "name1 name3"  
Rect3.name = "name2"  
```

So: 
`find('.name1.name3')`
should give me Rect2 as a result.

**Comment by GeorgeGkas** [comment]
I am quite skeptic regarding this feature, especially about the API we should provide to end users. In your example `find('.name1.name3')` matches exactly `Rect2`, and returns this instead of `Rect1`, but I do not see any reason why `Rect1` should not be also returned. 

Consider the following use case:

You develop a game and want to support basic shopping functionality for your hero (weapons, vehicles, etc). You want to add a filter option in the shop UI, to help the player filter the available vehicle types. He might need a simple car or a super vehicle that is both car, boat and airplane.

As developer, you will write something like this:

```js
Rect1.name = 'vehicle car'
Rect2.name = 'vehicle boat'
Rect3.name = 'vehicle car boat' // 007 super car
```

Assume that we want to find all the car vehicles using `find('.vehicle.car')`. These are the available return options:

1. Return only exact matches, in our case return `Rect1`.
2. Return non strict matches, matches that contain both `.vehicle` and `.car` without worrying for additional names that can exist in objects, in our case both `Rect1` and `Rect2`.
3. Let the developer decide by providing an additional option parameter to `find` with the following flag:
    - `exact: boolean`: When is set to `true` return exact matches. When is set to `false` return non strict matches. 

The third option change the API of `find` like so `find('.name1.name2', { exact: false })` which is overwhelming for the end user (and to maintainers of this repo who need to track a lot of changes).
The second option is the best among the three. This isn't as strict as supporting only exact matches and save us from the need to change the API of the `find` method.

Another concept to consider is what happens in partial matches. Assume that I want to match `find('.vehicle.rocket')`. We see that `.vehicle` selector match `Rect1`, `Rect2` and `Rect3`, but none of them match `.rocket`. The return options are:

1. Return nothing, objects MUST exactly match the provided selector, in our case `.vehicle.rocket`.
2. Match as many names as possible requiring only one match to return. In our case return  `Rect1`, `Rect2` and `Rect3` because match `.vehicle` without worrying that they do not match `.rocket`.
3. Let the developer decide.

For this case, I think the first option is the only suitable.

To conclude, `find` will keep the same API, but will be able to match more than one names. To return a result, `find` MUST match exactly the names provided in the selector with the corresponding objects. Objects are returned when their name match exactly the selector, without worrying if they contain more names that do not match.

I want to here your opinions about this.

**Comment by lavrton** [comment]
Currently, I don't think we need to overload `find` methods with many options and selector abbilities. Just keep it simple for one name or id or class name (in case of string selector). 

Because right now we already have a very powerful way to express the selector with a function:

```javascript
group.find((node) => {
   return node.hasName('vehicle') && node.hasName('rocket');
});

group.find((node) => {
   return node.hasName('vehicle') || node.hasName('rocket');
});
```
