### ISSUE TITLE
Multi-touch and gestures support

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#607]
At the current moment, `Konva` supports only "one-pointer" input: mouse or single finger touch.

That is enough for almost all app, but sometimes it is nice to have full multi-touch support.
We can use multi-touch on native DOM container of the `Stage`, but it is not enough for shapes-level interactions.

I think we should add full low-level multitouch support for all `Konva` nodes. And then we can adopt a gesture javascript library, that can use low-level events (such as `touchstart`, `touchmove` and `touchend`) to fire "high-level" gesture events (such as `swipe` or `pinch`).

**Comment by VividWombat** [comment]
would be a nice addition

resizing on tablet/phone is usually with multi touch, so support for that would be good

perhaps at the same time you can look at why touch events produce different results than mouse events, and get consistent results. or at least document what the differences are, so they can be handled correctly. I assume this is due to underlying touch events in HTML5 being different

**Comment by lavrton** [comment]
Konva now has much better support of multitouch events.

Here is the attempt to integrate it with a gesture library: https://konvajs.org/docs/sandbox/Gestures.html
