### ISSUE TITLE
Animation stuttering

### ISSUE THREAD

**Issue by kubajaburek** [konvajs/konva#636]
Hi,
I’m creating a weather animation for a website (almost fullscreen canvas). Currently I’m dealing with performance issues when animating a rainfall, in particular the animation renders choppy. I’m using Konva 3.2.4 with FastLayers and I’ve checked and there doesn’t seem to be any memory leaks or performance issues with my animation function.

Here’s a demo: [https://jsbin.com/keziruvaku/edit?js,output](https://jsbin.com/keziruvaku/edit?js,output)

I’m trying to make 30 vector raindrops fall repeatedly from the top of the screen, but the animation stutters even on a decent laptop (Intel Core i7 and 16 GB of RAM) when running in Chrome and lags even more in Edge and Firefox.

This is my first time developing an animation, so I’m not sure whether I missed something obvious or the script should be written in a completely different way, but I’ve tried to make as much performance optimizations as I could.

Thank you for your help.

**Comment by lavrton** [comment]
From the Konva side, you may decrease canvas size with `Konva.pixelRatio = 1`. That will make the canvas a bit blurred but should improve the performance on HDPI devices (retina). I think the issue is in a very large canvas.

Currently, I don't see any other possible ways. Only to rewrite that animation into native canvas without Konva. It should not be hard.
