### ISSUE TITLE
[Feature] 2D Shape Deformation (e.g. for characters)

### ISSUE THREAD

**Issue by Ivanca** [konvajs/konva#658]
![image](https://user-images.githubusercontent.com/907138/58674581-1f59aa80-8316-11e9-8d90-901980f54031.png)

There are various ways to implement such feature, here is a paper on one called "2D Shape Deformation Using Nonlinear Least Squares Optimization": http://kunzhou.net/publications/2DShape.pdf ([C++ implementation](https://github.com/Yiphy/Ransac-2d-Shape-Detection))

There is an open-source animation suite called [synfig](https://github.com/synfig/synfig/) that implements this feature as well (using C++)

A project I'm working on needs this feature, I understand that it may be hard to implement and it may be a feature few users want so I'm willing to negotiate a price to implement it.

**Comment by lavrton** [comment]
That looks interesting. But, yeah, I don't think we need such functionality in Konva core codebase.
As there is C++ implementation it is possible to convert it into JS code with something like emscripten.

Then you can use it to draw generated image into a canvas element. The canvas element can be used for `Konva.Image` or `Konva.Sprite`.

**Comment by Ivanca** [comment]
What a total lack of ambition, well is your library so its your call.

**Comment by lavrton** [comment]
Well, I have no idea how to use it with Konva and how to implement it. If you have any specific ideas I am happy to discuss them.

From what I understand it requires a huge amount of code. That means it will be hard to insert it into to Konva, because Konva (or any other js lib) should be as small as possible. So it is better to implement it as a stand-alone library.
