### ISSUE TITLE
Line's dragBoundFunc doesn't receive absolute position

### ISSUE THREAD

**Issue by cajicsym** [konvajs/konva#750]
All other shapes receive the absolute position of the shape on the canvas, but `Line` doesn't. It always starts from position `x: 0, y: 0`. 

I am trying to prevent the shape from moving outside of canvas, and I tried to solve it using shape's `getClientRect()`, which gives me the absolute position, but when utilizing that there is some weird shaky not-really-working effect when trying to move the shape outside of canvas. 

https://jsbin.com/kixiyaqapu/edit?js,console,output (try to move the shape to left or top edge)

Is there any workaround for this issue?

**Comment by lavrton** [comment]
`getClientRect()` is not an absolute position of the node. That function just calculates bounding box of the shape. It may look similar to `node.absolutePosition()` but it has different values. Especially for a line.

There is a function `line.getSelfRect();` that can be used to calculate the "offset" of the shape from its position.

```javascript
dragBoundFunc: function(pos) {
    const selfRect = line.getSelfRect();
    
    const minX = -selfRect.x;
    const maxX = stage.width() - (selfRect.x + selfRect.width);
    
    const minY = -selfRect.y;
    const maxY = stage.height() - (selfRect.y + selfRect.height);
   
    
    return {
      x: Math.min(maxX, Math.max(minX, pos.x)),
      y: Math.min(maxY, Math.max(minY, pos.y)),
    };
  }
```

https://jsbin.com/hexirisihu/edit?js,output

**Comment by evanthebouncy** [comment]
it is still a very surprising behaviour that most other geometry's .x() and .y() performs one way, yet line's is completely different in an unexpected way. I just tried out the getSelfRect() function, it behave on arc / rectangles one way, and again differently on line.

so line really is an odd-ball of the group, it is unclear what is the motivation for this distinction. my work-around currently is to not even render the line, but to render a narrow rectangle in its place, doing some math to rotate it, so that I can treat all geometries on my canvas the same way w.r.t. dragend and .x() and .y().

**Comment by lavrton** [comment]
I am not certain why you mentioned that `x` and `y` works differently. It works the same way. You just need to understand that `points` are relative. They can start from any point/distance from origin of the line (its `x` and `y`).

**Comment by vovabasket97** [comment]
@lavrton But this is doesn't work if add rotation to line. 
Can u help, how to fix it? 
U can check here - https://jsbin.com/zozamimuro/1/edit?js,output
