### ISSUE TITLE
[Feature request] Text padding with different values

### ISSUE THREAD

**Issue by Flashunt** [konvajs/konva#755]
Hi, i have a feature request.
Currently only one number value can added to a Konva.Text config, but i need change the padding with different values on each side of the Text object.
Can implement an additional object? Just like this:
`
padding?: number | { top: number, left: number, bottom: number, right: number };
`

**Comment by ertugrulcetin** [comment]
@lavrton that would be great

**Comment by lavrton** [comment]
I am closing the issue, because I don't see much value in this feature. It will complicate the API and internal code.

If you need different paddings from top, left, right, bottom just calculate position of the text manually and set correct x, y position.

If someone still need the issue, you can try to make a pull request. But the code change somehow should be very simple. Text shape is already complex.
