### ISSUE TITLE
[Optimization Request] GetImageData()

### ISSUE THREAD

**Issue by 17b0080** [konvajs/konva#801]
Hello, function (callback) getImageData takes ~40-60ms on a big resolution (4k). I haven't found any possible way in the documentation how to remove window events on wheel and mouse which causes this callback. Would there be any option how to remove this events?

**Comment by lavrton** [comment]
Usually, it works super fast. What browser are you using? `getImageData` is used for hit detection.

**Comment by 17b0080** [comment]
Opera/Firefox, situation seems better for Chrome

**Comment by lavrton** [comment]
@17b0080 will you have any differences if you try to decrease the pixel ratio of hit canvas:
```
layer.hitCanvas.setPixelRatio(0.2);
```
Can you try such a trick?

**Comment by lavrton** [comment]
Currently, I don't see any simple ways to use different hit testing algorithms in Konva.  If you still have issues with it, please try trick above.

**Comment by eXponenta** [comment]
Why can't use a simple rect-point test before getImageData? Basically not needed use a pixel-to-pixel hit detection, using a approximated rect is useful in a lot of cases.
This will reduce draw operations too.

**Comment by lavrton** [comment]
@eXponenta I am happy to review any related Pull Request if they will performance.

**Comment by eXponenta** [comment]
Ok, try to prepare it, but looks like will be major change.

**Comment by lavrton** [comment]
You are right. **It is a very major change.** And I am uncertain if it will work faster. It may work faster in some cases, but much slower in others.
Just a quick example is here: https://konvajs.org/docs/sandbox/10000_Shapes_with_Tooltip.html

Hit canvas for 10 000 shapes is rendered just once. Then we can use it to enable events and do hit testing. We don't need to redraw anything there. Doing a rect-point test on every mouse move may be MUCH slower. 
So, it is a very open question what is faster. Just draw everything or do math-powered hit testing.

**Comment by eXponenta** [comment]
Yep, this is faster when not changed.
If a canvas will updates each frame like rotation - getImageData drop all performance.
QuadTree more effective when all is reconstructed often.
Atm we have a problems for application where used scale animation via `to`, and when it is scaling - canvas is extrimelly slow, because each redraw drop getImageData cache.

I thought should be way to use a custom hit func like a `hitTestFunc` which will called when a hit test runs for shape, or disable a hitCanvas for layer and use only mathematical operaitons. 

Atm more problem that there are a 2 draws pass: main render + hit canvas render, yep, use a scale ratio about 0.2 can solve some problem but not for all cases.

I still hope to find optimal way to increase our app performance without core modification (already thought about Web Workers for konva content)

**Comment by eXponenta** [comment]
OffscreenCanvas has extremely low performance in getImageData

https://jsfiddle.net/n3y1w9ha/
