### ISSUE TITLE
I am fabric user planning to migrate to konva

### ISSUE THREAD

**Issue by iamappmaker** [konvajs/konva#812]
I created a graphic design application using fabricjs. only thing i worried is performance. When i add HD image and do any operations, performance drops and most of the time getting hang. So i like to migrate to konva but we have many json files, is it possible to convert fabric json to konva json format so i can import my fabricjs projects.

**Comment by lavrton** [comment]
> only thing i worried is performance

Before migration makes sure `Konva` can provide better performance.  Personally I am not sure about it, because fabric and Kovna work very similar. I think you can try to decrease image resolution in some cases.

> is it possible to convert fabric json to konva json

I don't know the fabric format and what properties they use. But you can try to do it. Just compare them manually and write your own converter.

Any way for storing objects it is better to use your own JSON format, so it independent from the framework. 

https://konvajs.org/docs/data_and_serialization/Best_Practices.htm
