### ISSUE TITLE
Video Performance

### ISSUE THREAD

**Issue by rebinnaf** [konvajs/konva#847]
I use konva image to play a video and it slows down the frame rate when animation is started either the video is playing or paused. I was wondering if there is anyway not to use animation start and stop in video playing. Since I want to seek the video frame by frame and this is possible by setting current time, I must stop and start the animation on each frame change to improve the performance. On the other hand, HTML video player does not have any event that shows the frame has been loaded; So, I did not find a proper way to stop the animation if the frame changes.

I use the drag and zoom feature of konva. So, I am not able to use video and absolute position too.

**Comment by lavrton** [comment]
In this demo https://konvajs.org/docs/sandbox/Video_On_Canvas.html, I am using animation to redraw the layer. Otherwise, it will be static.

If you change the frame of the video manually you can just call `layer.batchDraw()` once.

> video player does not have any event that shows the frame has been loaded

Yeah. that is a hard part here. I don't know full video element spec here, so I am not sure what to do when a frame is just not loaded yet.

**Comment by rebinnaf** [comment]
Thanks, very helpful.
