### ISSUE TITLE
Konva.Text fillPattern

### ISSUE THREAD

**Issue by monumatik** [konvajs/konva#852]
Hi,
i try to use fillPatern attributes e.g. "fillPatternOffsetX" in Konva.Text ? 
I'm trying to move only fillPattern, but when i set fillPatternOffsetX in Text constructor it moves whole text.

**Comment by lavrton** [comment]
There is no good solution to this issue right now.

As a workaround, you can try to draw text with  https://konvajs.org/docs/styling/Blend_Mode.html. So you can "cut" text from the background image.

Or you can try to move the pattern manually, with something like this:
```javascript
const pattern = text._getFillPattern();
pattern.setTransform({
        a: text.fillPatternScaleX(), // Horizontal scaling. A value of 1 results in no scaling.
        b: 0, // Vertical skewing.
        c: 0, // Horizontal skewing.
        d: text.fillPatternScaleY(), // Vertical scaling. A value of 1 results in no scaling.
        e: text.fillPatternOffsetX(), // Horizontal translation (moving).
        f: text.fillPatternOffsetY() // Vertical translation (moving).
 });
```

But it doesn't work in all browsers (so that is why it is not included into Konva core yet).
