### ISSUE TITLE
300 DPI Image Export

### ISSUE THREAD

**Issue by waliarubal** [konvajs/konva#859]
I have exported image of canvas by the 'toDataURL' method you provide, the generated image is just 72 DPI. I am even setting pixel ratio 1 while exporting as instructed in help page. I want to export my canvas as a 300 DPI image. Do let me know how do I get 300 DPI image for printing?

Since my client sends the final image to printer and it comes out super bad because of 72 DPI, he is expecting 300 DPI images.

**Comment by lavrton** [comment]
`Konva` doesn't use the DPI term in the API. It has just pixels. If you need more pixels for export (to make the resulted image bigger) you can use `pixelRatio` attribute.

So with `pixelRatio = 2` the image will have 4x more pixels. It is 4x bigger because  2x of `width` and 2x of `height`.

Probably something like this will work:

```javascript
state.toDataURL({ pixelRatio: 300 / 72})
```

Let me know if it helps.

**Comment by waliarubal** [comment]
Thanks @ivan-redooc  for giving the clarification, I have applied the code which you suggested for now. Will try some GDI+ code at server side to generate the images to get them 300 DPI.
