### ISSUE TITLE
how to access internal Function with TypeScript?

### ISSUE THREAD

**Issue by WilkinWendy** [konvajs/konva#885]
Some internal  functions like  Factory are really good tools ,
How can i get it? I use Typescript

**Comment by lavrton** [comment]
Why do you need it? What functions?

I am not sure I want to show `Factory` into public API.

**Comment by WilkinWendy** [comment]
ehhh, I customed a shape using typescript.
I want some internal functions 
Like:
1. addGetterSetter to  make my work convenient
2. _registerNode to use Node._createNode
... and so on

**Comment by lavrton** [comment]
Closing as not a priority right now. I am not sure Konva should be designed to create/register custom shapes with Konva internals.

**Comment by gus4no** [comment]
Yup, same here. I ended up having my custom transformer to handle line/arrow resize, so I add 2 anchors at the start/end of the line and I can resize/reposition the line, rather than scale it up/down as the current Transformer does. 

I implemented some copy/paste controls in my app, and when I save the node as JSON its properly saved with the `className` I need, however when I use `Konva.Node.create(json)` it creates a `Shape` rather than my custom shape class `LineTransformer`, I noticed this happen because my class is not in the registry so I'd like to add it with `_registerNode`. 

Is there another way I could do this?
