### ISSUE TITLE
Font faces with a number in the name are not working in Konva Text

### ISSUE THREAD

**Issue by beatgutzwiller** [konvajs/konva#910]
@font-faces with a number in the name are not loaded correctly:

https://jsbin.com/becakowiwi/edit?html,css,js,output

It works if there is no number in it (Note: Press 'run' twice, it has no loading callback):

https://jsbin.com/loqipexuho/edit

Since I am using a font imported by a ruby gem, I have to use the number.

**Comment by lavrton** [comment]
Will be fixed in the next version. As workaround FOR CURRENT version you can use this:

`fontFamily: '"Font Awesome 5"'` (wrap into `"`);

**Comment by taion** [comment]
With the fix to automatically wrap fonts in quotes, it's now not possible to non-awkwardly specify e.g. a list of fonts like `font1,font2`, as the quoting logic would turn that into `"font1,font2"`. It seems like it would make more sense, then, for `fontFamily` to behave like CSS `font-family` and in fact to require quoting multi-word font names, say.

**Comment by lavrton** [comment]
Interesting. Am I understanding right that for such fonts we don't need quotes or make it like `"font1","font2"`? Can you make a demo of the issue?

**Comment by taion** [comment]
It's just like in CSS `font-family` properties. You can do something like `ctx.font = '"Open Sans", sans-serif'` (or in Konva v6, set `fontFamily` to e.g. `'"Open Sans", sans-serif'`) and get the CSS-like behavior where, in this example, if "Open Sans" were unavailable, the text would use `sans-serif` instead.

In our specific use case, we were setting `fontFamily` to `Biotif,sans-serif`; in v6, this translated into a call to `ctx.font = 'Biotif,sans-serif'`, which gave us the desired behavior (Biotif if the webfont is loaded, sans-serif otherwise). In v7, this becomes a call to `ctx.font = '"Biotif,sans-serif"'`, which does not.

**Comment by taion** [comment]
I can post a CodeSandbox or something if that would help, but does my description above make sense?

**Comment by lavrton** [comment]
It makes sense. Let me think about how to resolve for better support of both cases.

**Comment by taion** [comment]
I have no idea how we'd implement this in JS, but the logic for `style.fontFamily` seems close to ideal:

![image](https://user-images.githubusercontent.com/3112159/85638479-fc521500-b653-11ea-8c7f-2696ef4aab9d.png)

**Comment by lavrton** [comment]
I will make a release later.
